### ISSUE TITLE
Use unittests in the test folder

### ISSUE THREAD

**Issue by philip-sterne** [guydav/minsketch#2]
See examples here:
http://www.onlamp.com/pub/a/python/2004/12/02/tdd_pyunit.html
http://www.onlamp.com/pub/a/python/2005/02/03/tdd_pyunit2.html
http://docs.python-guide.org/en/latest/writing/tests/
https://docs.python.org/2/library/unittest.html

If I remember correctly nose is even better, but plain old `unittest` is already good enough.
http://pythontesting.net/framework/nose/nose-introduction/

**Comment by guydav** [comment]
Converted the test code to run as nose unit tests as follows:

nosetests -v test/cm_sketch_test.py

Working on integrating it with CircleCI as well - will require figuring out the same install dependencies issue that's plaguing read the docs. See issue #1
